
# This file was automatically created from localization JSON files.
# DO NOT EDIT THIS FILE DIRECTLY. If you want to edit a translation, please use the language's JSON file.

from typing import Literal, List
Language=Literal['en', 'fi']
languages: List[Language] = ['en', 'fi']
default_lang: Language | str='en'
def change_language(new_lang: Language | str) -> None: global default_lang; default_lang = new_lang
def user_intro(user,lang:str|None=None):
	if not lang: lang=default_lang
	if lang == "en": return "Hello, {user}".format_map({"user": user})
	if lang == "fi": return "Hei, {user}".format_map({"user": user})
	else: raise ValueError(f'Invalid language {lang}')
def description(lang:str|None=None):
	if not lang: lang=default_lang
	if lang == "en": return "You can manage your account settings here"
	if lang == "fi": return "Voit hallitä käyttäjäsi asetuksia täältä"
	else: raise ValueError(f'Invalid language {lang}')
